quarkus.http.host=0.0.0.0
quarkus.http.port=8081
quarkus.log.level=INFO

quarkus.container-image.build=false
quarkus.container-image.group=demo
quarkus.container-image.name=greeting-app
quarkus.container-image.tag=latest

quarkus.docker.dockerfile-jvm-path=src/main/docker/Dockerfile.jvm
